### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by seiyab** [seiyab/vim-gym#1]
- [x] setup React project
- [x] Let Vim works
- [x] Open an file
- [x] Show diff
- [x] Several files
- [x] Run Prettier on app
- [x] Check correctness
