### ISSUE TITLE
Milestones 2

### ISSUE THREAD

**Issue by seiyab** [seiyab/vim-gym#2]
- [x] Party popper
- [x] Prevent overflow in diff
- [ ] Side margin
- [ ] Show metadata of tasks
- [ ] Task object generation
- [ ] Add 5+ tasks
- [ ] Word-level diff
- [ ] Line number in diff
- [ ] Faster diff
